### ISSUE TITLE
I can't create label

### ISSUE THREAD

**Issue by tkd89** [alexfraundorf-com/ship#3]
Hi,
first at all, I would like to thank you for your working, really great job :)

I would like to use yours project in my solution and I have problem with creating label.
I live in Poland, shipping from Warsaw, by UPS. I have UPS account and api key.
 
When I trying to create label following by your example, get some error:

<code>  Error: UPS SOAP Request failed - An exception has been raised as a result of client data. - Serialized Details: O:8:"stdClass":2:{s:8:"Severity";s:4:"Hard";s:16:"PrimaryErrorCode";O:8:"stdClass":2:{s:4:"Code";s:6:"120598";s:11:"Description";s:80:"Package Delivery Confimation is not allowed with the shipment origin/destination";}}  </code>

and I don't know where is the problem, all informations include in config.php file is correct and match with information in UPS account.

**Comment by alexfraundorf-com** [comment]
Not a bug.  Closed.
