### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by redknite** [alexfraundorf-com/ship#8]
I am excited about this program and want to try it but when i do i get this error:
Fatal error: Class 'libs\Awsp\Ship\Shipment' not found in /public_html/thexpress/get_rates_example.php on line 64"

**Comment by naeem084** [comment]
Hello guys,

I am facing the same Fatal error: Class 'libs\Awsp\Ship\Shipment' not found in /public_html/thexpress/get_rates_example.php on line 64" even i set the path in config.php as well. please guide me what should i do next to solve.

**Comment by alexfraundorf-com** [comment]
Hello,
It looks like you are using the file path from the previous person's set up
(thexpress).
Make sure to define the SHIP_PATH constant (line 18 in
ship/includes/config.php) to the path on your server.
Please feel free to email me if you need any additional help.
Thanks!


Alex Fraundorf
(920) 725-2103
AlexFraundorf.com
SnapProgramming.com

**Comment by naeem084** [comment]
Thanks a lot for replay i was really struggling to find the solution.

this is my line number 18: define('SHIP_PATH', 'http://localhost/ship-master/libs/');

**Comment by alexfraundorf-com** [comment]
You are welcome.
The path needs to be absolute based on your file structure (no http://).
It is probably something like /public_html/ship-master/libs.
You can try placing exit(__DIR__); at the top of the file that isn't
loading and it should echo out your directory structure.  If your server
uses a file manager, you can also find it there.
FYI: I am working on a new version that will support composer and will
solve this kind of issue :-)


Alex Fraundorf
(920) 725-2103
AlexFraundorf.com
SnapProgramming.com

**Comment by naeem084** [comment]
Wow that's working. i really appreciate your help and great work as well.
Thank you so much.

**Comment by alexfraundorf-com** [comment]
You are very welcome.
Happy PHPing!


Alex Fraundorf
(920) 725-2103
AlexFraundorf.com
SnapProgramming.com
